# Generated by Django 2.2.5 on 2021-08-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210810_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='discriptions',
            new_name='description',
        ),
    ]
